services:
  web_server:
    image: 'ivolchenkov/mega-mailer-web-server'
    restart: unless-stopped
    volumes:
      - ./mega-mailer-src/config.yaml:/opt/mega-mailer/config.yaml
    ports:
      - '8000:8000'
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
  telegram_bot:
    image: 'ivolchenkov/mega-mailer-telegram-bot'
    restart: unless-stopped
    volumes:
      - ./mega-mailer-src/config.yaml:/opt/mega-mailer/config.yaml
    depends_on:
      web_server:
        condition: service_healthy
  mail_checker:
    image: 'ivolchenkov/mega-mailer-mail-checker'
    restart: unless-stopped
    volumes:
      - ./mega-mailer-src/config.yaml:/opt/mega-mailer/config.yaml
    depends_on:
      web_server:
        condition: service_healthy
  broker:
    image: 'ivolchenkov/mega-mailer-broker'
    restart: unless-stopped
    volumes:
      - ./mega-mailer-src/config.yaml:/opt/mega-mailer/config.yaml
    depends_on:
      web_server:
        condition: service_healthy

  redis:
    image: ghcr.io/dragonflydb/dragonfly:latest
    restart: unless-stopped
    # ports:
    #   - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5436:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 1s
      timeout: 3s
      retries: 5

